export enum EventCategory {
  CONCERT = 'CONCERT',
  CONFERENCE = 'CONFERENCE',
  WORKSHOP = 'WORKSHOP',
  SEMINAR = 'SEMINAR',
  FESTIVAL = 'FESTIVAL',
  SPORTS = 'SPORTS',
  THEATER = 'THEATER',
  OTHER = 'OTHER',
}

